# Generated by Django 3.2.2 on 2021-05-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
