# Generated by Django 3.2.2 on 2021-05-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_advisorbooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisorbooking',
            old_name='appointment_time',
            new_name='booking_time',
        ),
    ]
