# Generated by Django 3.2.2 on 2021-05-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_appointment_time_advisorbooking_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorbooking',
            name='booking_time',
            field=models.DateTimeField(),
        ),
    ]
